version: "3.7"

services:
  exchange:
    image: rust-grpc-exchange:1.0.0
    container_name: exchange
    volumes:
      - ./logs/exchange:/app/logs
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      PORT: 8001
